import { StatusParking } from './variable';

export const park: StatusParking[] = [
  {
    id: 1,
    lot_id: 'A001',
    licenseplate: '',
    status: 0,
    reservable: false,
    floor: 'A',
  },
  {
    id: 2,
    lot_id: 'A002',
    licenseplate: '',
    status: 1,
    reservable: false,
    floor: 'A',
  },
  {
    id: 3,
    lot_id: 'A003',
    licenseplate: '',
    status: 0,
    reservable: false,
    floor: 'A',
  },
  {
    id: 4,
    lot_id: 'A004',
    licenseplate: '',
    status: 0,
    reservable: false,
    floor: 'A',
  },
  {
    id: 5,
    lot_id: 'A005',
    licenseplate: '',
    status: 0,
    reservable: false,
    floor: 'A',
  },
  {
    id: 6,
    lot_id: 'A006',
    licenseplate: '',
    status: 0,
    reservable: false,
    floor: 'A',
  },
  {
    id: 7,
    lot_id: 'A007',
    licenseplate: '',
    status: 0,
    reservable: false,
    floor: 'A',
  },
  {
    id: 8,
    lot_id: 'A008',
    licenseplate: '',
    status: 0,
    reservable: true,
    floor: 'A',
  },
  {
    id: 9,
    lot_id: 'A009',
    licenseplate: '',
    status: 0,
    reservable: true,
    floor: 'A',
  },
  {
    id: 10,
    lot_id: 'A010',
    licenseplate: '',
    status: 0,
    reservable: true,
    floor: 'A',
  },
];

export const reserve: StatusParking[] = [
  {
    id: 8,
    lot_id: 'A008',
    licenseplate: '',
    status: 0,
    reservable: true,
    floor: 'A',
  },
  {
    id: 9,
    lot_id: 'A009',
    licenseplate: '',
    status: 0,
    reservable: true,
    floor: 'A',
  },
  {
    id: 10,
    lot_id: 'A010',
    licenseplate: '',
    status: 0,
    reservable: true,
    floor: 'A',
  },
];
